spring.application.name=job-platform

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/jobsdb}
spring.datasource.username=${DB_USER:jobs}
spring.datasource.password=${DB_PASSWORD:jobs}
spring.jpa.hibernate.ddl-auto=update